"""
api_spec.py
-----------
Parses `--help` output from Click-based CLIs and generates
a Markdown reference document (references/api_spec.md).

CLI entrypoints are read from pyproject.toml [project.scripts],
so any newly registered CLI is automatically included.

Usage:
    python -m scripts.api_spec
    # or directly:
    python work_tools/src/scripts/api_spec.py
"""

import re
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

# ── Path Configuration ───────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parents[3]  # taiga-task-writer/
REFERENCES_DIR = PROJECT_ROOT / "work_tools" / "references"
OUTPUT_FILE = REFERENCES_DIR / "api_spec.md"
PYPROJECT = PROJECT_ROOT / "pyproject.toml"


# ── CLI Discovery ────────────────────────────────────────────────────────────


def discover_cli_entrypoints() -> dict[str, str]:
    """Read [project.scripts] from pyproject.toml.

    Returns:
        A dict mapping CLI names to their entrypoint strings.
        e.g. {"taiga-cli": "modules.taiga.api:main", ...}
    """
    with open(PYPROJECT, "rb") as f:
        data = tomllib.load(f)
    return data.get("project", {}).get("scripts", {})


# ── Help Execution ───────────────────────────────────────────────────────────


def _run_help(cli_name: str, *args: str) -> str:
    """Run `<cli_name> [args] --help` and return stdout.

    Args:
        cli_name: The registered CLI command name.
        *args: Additional arguments (e.g. subcommand name).

    Returns:
        The help output string.
    """
    venv_bin = PROJECT_ROOT / ".venv" / "bin" / cli_name
    cmd = [str(venv_bin), *args, "--help"]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(PROJECT_ROOT))
    return (result.stdout or result.stderr).strip()


def _extract_click_subcommands(help_text: str) -> list[str]:
    """Extract subcommand names from Click's --help output.

    Args:
        help_text: The top-level --help output of a Click group.

    Returns:
        A sorted list of subcommand names.
    """
    commands: list[str] = []
    in_commands = False
    for line in help_text.splitlines():
        stripped = line.strip()
        if re.match(r"^Commands:", stripped, re.IGNORECASE):
            in_commands = True
            continue
        if in_commands:
            if not stripped:
                break
            m = re.match(r"^([\w-]+)", stripped)
            if m:
                commands.append(m.group(1))
    return sorted(commands)


# ── Markdown Generation ──────────────────────────────────────────────────────


def _build_cli_section(cli_name: str) -> list[str]:
    """Build Markdown section for a single CLI.

    Args:
        cli_name: The registered CLI command name.

    Returns:
        A list of Markdown lines for this CLI.
    """
    lines: list[str] = []
    top_help = _run_help(cli_name)

    lines.append(f"# `{cli_name}` – Command Reference")
    lines.append("")
    lines.append("```")
    lines.append(top_help)
    lines.append("```")
    lines.append("")

    subcommands = _extract_click_subcommands(top_help)
    if not subcommands:
        return lines

    lines.append("## Commands")
    lines.append("")
    for cmd in subcommands:
        lines.append(f"- `{cmd}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    for cmd in subcommands:
        sub_help = _run_help(cli_name, cmd)
        lines.append(f"### `{cli_name} {cmd}`")
        lines.append("")
        lines.append("```")
        lines.append(sub_help)
        lines.append("```")
        lines.append("")

    return lines


def _build_markdown(cli_names: list[str]) -> str:
    """Build the full Markdown document for all CLIs.

    Args:
        cli_names: List of CLI command names to document.

    Returns:
        The complete Markdown content as a string.
    """
    lines: list[str] = []
    lines.append("<!-- Auto-generated by scripts/api_spec.py — DO NOT EDIT -->")
    lines.append("")

    for i, cli_name in enumerate(cli_names):
        if i > 0:
            lines.append("---")
            lines.append("")
        lines.extend(_build_cli_section(cli_name))

    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────────────────────────


def main():
    """Entry point for the API spec generator."""
    entrypoints = discover_cli_entrypoints()
    if not entrypoints:
        print("No CLI entrypoints found in pyproject.toml [project.scripts].", file=sys.stderr)
        sys.exit(1)

    cli_names = sorted(entrypoints.keys())
    print(f"Found {len(cli_names)} CLI(s): {', '.join(cli_names)}")

    for name in cli_names:
        print(f"  Collecting --help for '{name}'...")
        top_help = _run_help(name)
        subcmds = _extract_click_subcommands(top_help)
        for cmd in subcmds:
            print(f"    {name} {cmd} --help")
            _run_help(name, cmd)

    md_content = _build_markdown(cli_names)

    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(md_content, encoding="utf-8")
    print(f"✅  Generated: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
