"""
api_spec.py
-----------
Parses --help output from Click-based CLIs and generates
a Markdown reference document (work_tools/references/api_spec.md).

Now optimized for the unified 'wt' CLI entry point.
"""

import re
import subprocess
from pathlib import Path

# ── Path Configuration ───────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parents[4]
REFERENCES_DIR = PROJECT_ROOT / "work_tools" / "references"
OUTPUT_FILE = REFERENCES_DIR / "api_spec.md"


# ── Help Execution ───────────────────────────────────────────────────────────


def _run_help(cli_name: str, *args: str) -> str:
    """Run `<cli_name> [args] --help` and return stdout."""
    # Security: Validate inputs to prevent command injection
    if cli_name != "wt":
        raise ValueError(f"Unauthorized cli_name: {cli_name}")

    for arg in args:
        if not re.match(r"^[a-zA-Z0-9_-]+$", arg):
            raise ValueError(f"Invalid character in argument: {arg}")

    # Try using 'uv run cli_name' for better compatibility with the environment
    cmd = ["uv", "run", cli_name, *args, "--help"]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(PROJECT_ROOT))
    if result.returncode != 0:
        # Fallback to direct venv call if uv run fails
        venv_bin = PROJECT_ROOT / ".venv" / "bin" / cli_name
        cmd = [str(venv_bin), *args, "--help"]
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(PROJECT_ROOT))

    return (result.stdout or result.stderr).strip()


def _extract_click_subcommands(help_text: str) -> list[str]:
    """Extract subcommand names from Click's --help output."""
    commands: list[str] = []
    in_commands = False
    for line in help_text.splitlines():
        stripped = line.strip()
        if re.match(r"^Commands:", stripped, re.IGNORECASE):
            in_commands = True
            continue
        if in_commands:
            if not stripped:
                break
            # Click commands usually start with the name followed by some space
            m = re.match(r"^([\w-]+)", stripped)
            if m:
                commands.append(m.group(1))
    return sorted(commands)


# ── Markdown Generation ──────────────────────────────────────────────────────


def _document_command(cli_name: str, cmd_path: list[str], lines: list[str], level: int = 1) -> None:
    """Recursively document a command and its subcommands.

    Args:
        cli_name: The base CLI command (e.g. 'wt').
        cmd_path: List of subcommand names to reach this point.
        lines: List of Markdown lines to append to.
        level: Current heading level (starts at 1 for #).
    """
    full_cmd = " ".join([cli_name] + cmd_path)
    help_text = _run_help(cli_name, *cmd_path)

    # Header
    prefix = "#" * level
    lines.append(f"{prefix} `{full_cmd}`")
    lines.append("")
    lines.append("```")
    lines.append(help_text)
    lines.append("```")
    lines.append("")

    subcommands = _extract_click_subcommands(help_text)
    if not subcommands:
        return

    # Document each subcommand recursively
    for sub in subcommands:
        _document_command(cli_name, cmd_path + [sub], lines, level + 1)
        # Add a separator after second-level commands for readability
        if level == 1:
            lines.append("---")
            lines.append("")


def main():
    """Entry point for the API spec generator."""
    print("Generating API specification for 'wt'...")

    lines = [
        "<!-- Auto-generated by wt dev gen-spec — DO NOT EDIT -->",
        "",
        "# Work Tools CLI Reference",
        "",
        "This document is automatically generated from the `--help` output of the `wt` command.",
        "",
    ]

    _document_command("wt", [], lines)

    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅  Generated: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
